### ISSUE TITLE
2021 Roadmap

### ISSUE THREAD

**Issue by daybrush** [daybrush/moveable#391]
## My main project is `Scena`

http://github.com/daybrush/scena

I will release Moveable 1.0.0 in 2021

* [x] **Support Original Transform** (ex: `e.setTransform(`translate() scale() rotate()`)
* [x] Support lit framework
* [x] Support Vue 2 & Vue 3 (https://github.com/daybrush/moveable/issues/463)
* [x] Support framework components that are more fit (container issue)
* [ ] Prepare All framework's demos

If there is a feature you want, please participate in an issue or discussion

https://github.com/daybrush/moveable/discussions/393

**Comment by alezzigo** [comment]
Hi Bro, 
Moveable is great library. Thank @daybrush. 
Can you add feature Crop https://github.com/daybrush/moveable/issues/190#issuecomment-593714631.

**Comment by daybrush** [comment]
@alezzigo 

See this demo:
https://daybrush.com/moveable/storybook/?path=/story/nested-transform--cliappable

**Comment by alezzigo** [comment]
Nice @daybrush

**Comment by ilyes24** [comment]
@daybrush 

Hello, your work is outstanding, thank you very much.

Can you please guide me in the following issue #390

**Comment by zaqqaz** [comment]
Maybe we can add snapAngles for rotation ? 😉 
Common ux when we press meta button expected rotation behaviour is 0deg, 90deg, 180deg, (360)0deg.

**Comment by nelsondude** [comment]
https://github.com/daybrush/moveable/issues/397 - would be awesome to allow for more granular custom styling

**Comment by nelsondude** [comment]
Would also be great if you could add `centerVertical: boolean; centerHorizontal: boolean;` to `ElementGuidelineValue` so that we could choose if we want to snap to the center as well

**Comment by tianyuya** [comment]
There are multiple elements in the canvas, and some of them belong to a group. How do you determine if the blank area you click on is a group

**Comment by famibee** [comment]
If you drag two overlapping Moveables (which can be determined by mov.isInside()), both will move, so
I want mov.dragEnd() to kill the event in mov.on('dragStart', () => {}).

二つ重なったMoveable（これは mov.isInside() で判定できる）をドラッグすると両方動いてしまうので、mov.on('dragStart', ()=>{})内でイベントを強制終了させる mov.dragEnd() が欲しいです。

**Comment by famibee** [comment]
I want to change the verticalGuidelines and horizontalGuidelines at the time of onDragStart().
Currently, you can probably set the readonly attribute in an informal way (Object.assign).

onDragStart() 時に verticalGuidelines と horizontalGuidelines を変更したいです。
現状、恐らく非公式の方法（Object.assign）で readonly属性に設定できています。

Object.assign(this.mov, {
	verticalGuidelines	: aBtn.map(b=> b.x),
	horizontalGuidelines: aBtn.map(b=> b.y),
});
