### ISSUE TITLE
Todo 1.0.0

### ISSUE THREAD

**Issue by daybrush** [daybrush/moveable#702]
### Todo
1. [ ] All Framework Demo (Not yet)
2. [ ] Release `Snappable`
3. [ ] Improve the accuracy of guidelines #592 #617
4. [ ] Prepare 1.0 Migration docs https://github.com/daybrush/moveable/wiki/Migration-0.X-to-1.0
5. [ ] Solve `backlog`s https://github.com/daybrush/moveable/issues?q=is%3Aissue+is%3Aopen+label%3Abacklog
6. [ ] Support async state, transform.

### Maybe 1.0 major changes
1. Separate the minor ables(`warpable`, `clippable`, `originDraggable`, `roundable`) to modules and you can install by npm.
2. Remove unused props and texts. 
3. Add all-in-one events and how-tos

**Comment by hoondeveloper** [comment]
i am looking forward to release 1.0 💘
